#!/usr/bin/env python3
"""
fix_p0_tech_debt.py — 数据驱动的 P0 修复脚本

读 audit JSON → 应用 212 vars 补全 + 5 文件外溢规则删除

退出码: 0 = 成功; 1 = audit JSON 缺失; 2 = 工具故障
"""
import json
import shutil
import sys
from datetime import date
from pathlib import Path

from scripts.inference_rules import infer_value

ROOT = Path(__file__).parent.parent
OUTPUT_DIR = ROOT / "output"
CSS_DIR = ROOT / "css"
TOKENS_FILE = CSS_DIR / "tokens.css"
TOKENS_BAK = CSS_DIR / "tokens.css.bak-pre-p0-fix"

AUDIT_UNDEFINED = OUTPUT_DIR / "audit_undefined_css_vars.json"
AUDIT_COMPOUND = OUTPUT_DIR / "audit_compound_selectors.json"


def extract_p0_vars(audit_undefined: dict) -> list[str]:
    """从 audit_undefined_css_vars.json 提取 truly_undefined 类别的 var 名"""
    items = audit_undefined.get("items", [])
    return sorted(
        item["var"] for item in items
        if item.get("category") == "truly_undefined"
    )


def extract_overflow_files(audit_compound: dict) -> dict[str, list[dict]]:
    """从 audit_compound_selectors.json 提取 allowed==false 的文件及其 hits"""
    offenders = audit_compound.get("offending_files", [])
    return {
        f["file"]: f["hits"]
        for f in offenders
        if not f.get("allowed", False)
    }


def build_tokens_appendix(vars_list: list[str]) -> str:
    """生成要追加到 tokens.css 的 :root 块"""
    lines = [
        "",
        f"/* P0 fix — auto-generated by fix_p0_tech_debt.py on {date.today().isoformat()} */",
        ":root {",
    ]
    for var in sorted(vars_list):
        value, source = infer_value(var)
        comment = "  /* TODO: refine color */" if source == "fallback" else ""
        lines.append(f"    --{var}: {value};{comment}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def delete_overflow_rule(css_file: Path, line_number: int, selector_text: str) -> int:
    """删除从 line_number 开始的完整规则块（选择器 + body + 闭合 }）

    Args:
        css_file: CSS 文件路径
        line_number: 选择器开始的 1-indexed 行号
        selector_text: 选择器文本（可能跨多行，含 \\n）

    Returns:
        删除的行数。越界返回 0。
    """
    text = css_file.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)

    if line_number < 1 or line_number > len(lines):
        return 0

    start_idx = line_number - 1  # 转 0-indexed

    # 从 start_idx 向前扫描，找匹配的 '}'
    depth = 0
    saw_open = False
    end_idx = None
    for i in range(start_idx, len(lines)):
        for ch in lines[i]:
            if ch == '{':
                depth += 1
                saw_open = True
            elif ch == '}':
                depth -= 1
                if saw_open and depth == 0:
                    end_idx = i
                    break
        if end_idx is not None:
            break

    if end_idx is None:
        return 0

    # 删除 start_idx 到 end_idx（含）的所有行
    kept = lines[:start_idx] + lines[end_idx + 1:]
    css_file.write_text("".join(kept), encoding="utf-8")
    return end_idx - start_idx + 1


def _load_or_exit(path: Path) -> dict | None:
    if not path.exists():
        print(f"❌ 缺少输入: {path}", file=sys.stderr)
        print(f"   请先运行: python scripts/audit_{path.stem.replace('audit_', '')}.py", file=sys.stderr)
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"❌ JSON 解析失败: {path}: {e}", file=sys.stderr)
        return None


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    # 1) 读 audit JSON
    audit_undef = _load_or_exit(AUDIT_UNDEFINED)
    audit_comp = _load_or_exit(AUDIT_COMPOUND)
    if audit_undef is None or audit_comp is None:
        return 1

    # 2) 提取 P0 列表
    p0_vars = extract_p0_vars(audit_undef)
    overflow = extract_overflow_files(audit_comp)
    print(f"📋 P0 vars to add: {len(p0_vars)}")
    print(f"📋 Overflow files to clean: {len(overflow)}")

    # 3) 备份 tokens.css
    if not TOKENS_BAK.exists():
        shutil.copy2(TOKENS_FILE, TOKENS_BAK)
        print(f"💾 Backup created: {TOKENS_BAK.name}")

    # 4) 追加 212 vars 到 tokens.css
    appendix = build_tokens_appendix(p0_vars)
    with open(TOKENS_FILE, "a", encoding="utf-8") as f:
        f.write(appendix)
    print(f"✏️  Appended {len(p0_vars)} vars to {TOKENS_FILE.name}")

    # 5) 删除外溢文件的完整规则块
    # 注意：按行号倒序处理，避免前面的删除让后面的行号错位
    for fname, hits in overflow.items():
        css_file = CSS_DIR / fname
        if not css_file.exists():
            print(f"⚠️  {fname} not found, skip")
            continue
        sorted_hits = sorted(
            (h for h in hits if "line" in h and "selector" in h),
            key=lambda h: h["line"],
            reverse=True,
        )
        total_lines = 0
        for h in sorted_hits:
            n = delete_overflow_rule(css_file, h["line"], h["selector"])
            total_lines += n
        print(f"✏️  Cleaned {len(sorted_hits)} rules ({total_lines} lines) from {fname}")

    # 6) 摘要
    print()
    print("✅ P0 修复应用完成")
    print(f"   vars: +{len(p0_vars)} in tokens.css")
    print(f"   files: {len(overflow)} overflow files cleaned")
    print(f"   backup: {TOKENS_BAK.name} (gitignored)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
