# Star-Learn (星识) launcher.
# Invoked by the Windows shortcut as:  python.exe launcher.py
# Sets up per-user data, environment, then runs the FastAPI app in-process.
from __future__ import annotations

import logging
import os
import shutil
import socket
import sys
import threading
import time
import urllib.error
import urllib.request
import webbrowser
from pathlib import Path

LOG = logging.getLogger("starlearn.launcher")

INSTALL_DIR = Path(__file__).resolve().parent
USER_DATA = Path(os.environ.get("APPDATA", str(Path.home()))) / "StarLearn"
DB_FILE = USER_DATA / "xingshi.db"
ENV_FILE = USER_DATA / ".env"

# Inline fallback starter .env, used only if packaging/templates/starter.env is
# missing in this build (defensive — should never happen in shipped installs).
_DEFAULT_STARTER_ENV = (
    "# Auto-generated by Star-Learn launcher on first run.\n"
    "# Edit values below and restart the app to apply.\n"
    "STARLEARN_DB_BACKEND=sqlite\n"
    "SQLITE_PATH={db}\n"
    "DATABASE_URL=sqlite+aiosqlite:///{db_url}\n"
    "\n"
    "# ---- API keys (paste your own, leave blank if you don't use the feature) ----\n"
    "# XUNFEI_API_KEY=\n"
    "# MINIMAX_API_KEY=\n"
    "# MINIMAX_GROUP_ID=\n"
    "# BAIDU_ASR_API_KEY=\n"
    "# BAIDU_ASR_SECRET_KEY=\n"
    "# KLING_ACCESS_KEY=\n"
    "# KLING_SECRET_KEY=\n"
).format(db=DB_FILE, db_url=DB_FILE.as_posix())


# ---------- first-run user data setup ----------

def _ensure_user_data() -> None:
    USER_DATA.mkdir(parents=True, exist_ok=True)
    for sub in ("logs", "cache/audio", "cache/storage", "cache/agent_log_spool"):
        (USER_DATA / sub).mkdir(parents=True, exist_ok=True)

    if not ENV_FILE.exists():
        template = INSTALL_DIR / "packaging" / "templates" / "starter.env"
        if template.is_file():
            raw = template.read_text(encoding="utf-8")
            # Substitute placeholders so the user's .env is ready to use.
            raw = raw.replace("{DB_FILE}", str(DB_FILE))
            raw = raw.replace("{DB_FILE_URL}", DB_FILE.as_posix())
            ENV_FILE.write_text(raw, encoding="utf-8")
        else:
            ENV_FILE.write_text(_DEFAULT_STARTER_ENV, encoding="utf-8")


def _configure_env() -> None:
    os.environ["STARLEARN_USER_ENV"] = str(ENV_FILE)
    os.environ["STARLEARN_DB_BACKEND"] = "sqlite"
    os.environ["SQLITE_PATH"] = str(DB_FILE)
    os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{DB_FILE.as_posix()}"
    os.environ["LOCAL_STORAGE_PATH"] = str(USER_DATA / "local_storage.json")
    os.environ["XINSHI_AUDIT_LOG"] = str(USER_DATA / "logs" / "audit.log")
    os.environ["KB_BEHAVIOR_LOG_SPOOL_DIR"] = str(USER_DATA / "cache" / "agent_log_spool")
    os.environ["PYTHONUTF8"] = "1"
    os.environ["PYTHONIOENCODING"] = "utf-8"
    # PYTHONPATH must include INSTALL_DIR so `import app`, `import libs`, `import config` work.
    os.environ["PYTHONPATH"] = str(INSTALL_DIR) + os.pathsep + os.environ.get("PYTHONPATH", "")


# ---------- server readiness + auto-open browser ----------

def _wait_for_server(url: str, timeout: float = 30.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=1.0) as resp:
                # Any response from uvicorn (incl. 4xx) means the app finished
                # route registration. Don't gate on /docs specifically.
                if resp.status < 600:
                    return True
        except (urllib.error.URLError, ConnectionResetError, socket.timeout, OSError):
            time.sleep(0.25)
    return False


def _open_browser_when_ready() -> None:
    if _wait_for_server("http://127.0.0.1:8000/login.html", timeout=30.0):
        try:
            webbrowser.open("http://127.0.0.1:8000/login.html")
            LOG.info("browser opened")
        except Exception as exc:  # noqa: BLE001
            LOG.warning("webbrowser.open failed: %s", exc)
    else:
        LOG.warning("server did not come up within 30s; not opening browser")


# ---------- main ----------

def main() -> None:
    (USER_DATA / "logs").mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(message)s",
        filename=str(USER_DATA / "logs" / "launcher.log"),
        filemode="a",
    )
    # Embedded CPython may default to cp936 on Chinese Windows; force UTF-8.
    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name, None)
        if stream and hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8")
            except Exception:  # noqa: BLE001
                pass

    _ensure_user_data()
    _configure_env()
    # chdir BEFORE any `import main` so CWD-relative load_dotenv() finds the
    # user's .env in USER_DATA.  We do NOT delegate to start_server.py because
    # it does its own os.chdir() that would undo this.
    os.chdir(USER_DATA)
    LOG.info("INSTALL_DIR=%s | USER_DATA=%s", INSTALL_DIR, USER_DATA)

    # `db` and `config` modules are imported transitively by `main`. We import
    # `db` first so we can patch the module-level constants before any other
    # module does `from db import LOCAL_STORAGE_PATH`.
    import db  # noqa: E402
    db.LOCAL_STORAGE_PATH = str(USER_DATA / "local_storage.json")
    if hasattr(db, "BASE_DIR"):
        db.BASE_DIR = str(USER_DATA)

    import main as app_main  # noqa: E402
    import uvicorn  # noqa: E402

    threading.Thread(
        target=_open_browser_when_ready, daemon=True, name="browser-opener"
    ).start()

    uvicorn.run(
        app_main.app,
        host="127.0.0.1",
        port=8000,
        log_level="warning",
        access_log=False,
    )


if __name__ == "__main__":
    main()
