"""Repository Protocol definitions for database merge."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LearningRepository(Protocol):
    async def get_overview(self, user_id: str) -> dict: ...
    async def get_trend(self, user_id: str, days: int) -> list: ...
    async def get_heatmap(self, user_id: str) -> dict: ...
    async def record_session(self, user_id: str, session_data: dict) -> None: ...


@runtime_checkable
class PreferencesRepository(Protocol):
    async def get_preferences(self, user_id: str) -> dict: ...
    async def set_preference(self, user_id: str, key: str, value: dict) -> None: ...
    async def get_settings(self, user_id: str) -> dict: ...
    async def set_setting(self, user_id: str, key: str, value: str) -> None: ...
    async def get_theme(self, user_id: str) -> dict: ...
    async def set_theme(self, user_id: str, theme: str, accent_color: str = "#7c3aed") -> None: ...


@runtime_checkable
class ChatRepository(Protocol):
    async def save_message(self, user_id: str, message: dict) -> int: ...
    async def get_history(self, user_id: str, limit: int) -> list: ...
