"""Repository Protocol definitions for database merge."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LearningRepository(Protocol):
    async def get_overview(self, user_id: str) -> dict: ...
    async def get_trend(self, user_id: str, days: int) -> list: ...
    async def get_heatmap(self, user_id: str) -> dict: ...
    async def record_session(self, user_id: str, session_data: dict) -> None: ...
    async def save_learning_record(self, user_id: str, record: dict) -> int: ...
    async def get_learning_record(self, user_id: str) -> dict | None: ...
    async def save_user_evaluation(self, user_id: str, evaluation: dict) -> int: ...
    async def get_user_evaluation(self, user_id: str, record_date: str | None = None) -> dict | None: ...
    async def get_user_evaluation_history(self, user_id: str, days: int = 7) -> list: ...


@runtime_checkable
class PreferencesRepository(Protocol):
    async def get_preferences(self, user_id: str) -> dict: ...
    async def set_preference(self, user_id: str, key: str, value: dict) -> None: ...
    async def get_settings(self, user_id: str) -> dict: ...
    async def set_setting(self, user_id: str, key: str, value: str) -> None: ...
    async def get_theme(self, user_id: str) -> dict: ...
    async def set_theme(self, user_id: str, theme: str, accent_color: str = "#7c3aed") -> None: ...


@runtime_checkable
class ChatRepository(Protocol):
    def save_message(self, user_id, message: dict) -> int: ...
    def get_history(self, user_id, limit: int = 50) -> list: ...
    def save_memory(self, user_id, memory: dict) -> int: ...
    def get_memories(self, user_id, memory_type: str | None = None, limit: int = 20) -> list: ...
    def update_memory(self, memory_id: int, updates: dict) -> None: ...
    def confirm_memory(self, memory_id: int, confirmed: bool = True) -> None: ...
    def delete_memory(self, memory_id: int) -> None: ...
    def bump_memory_access(self, memory_id: int) -> None: ...


@runtime_checkable
class CourseProgressRepository(Protocol):
    def get_progress(self, user_id: str, course_id: str) -> dict | None: ...
    def save_progress(self, user_id: str, course_id: str, progress_percent: float, state: dict = None) -> None: ...
    def get_learning_path(self, user_id: str) -> list: ...
    def get_evaluations(self, user_id: str) -> list: ...
    def get_upcoming_deadlines(self, user_id: str, days: int = 7) -> list: ...
    # Learning-path graph ops (Task C1) — backed by db.py for now; ORM
    # implementation calls db.py helpers to keep behavior identical.
    def get_learning_path_graph(self, user_id) -> dict | None: ...
    def save_learning_path_graph(self, user_id, path_json, reasoning=None, data_sources=None, confidence=0.0) -> None: ...
    def get_learning_path_nodes(self, user_id) -> list: ...
    def get_learning_path_node(self, user_id, node_id) -> dict | None: ...
    def save_learning_path_node(self, user_id, node_data: dict) -> bool: ...
    def sync_path_to_nodes(self, user_id, path_json) -> int: ...
    # Daily task route (Task C1)
    def get_daily_route(self, user_id, route_date: str) -> dict | None: ...
    def save_daily_route(self, user_id, route_date: str, tasks, completed=None) -> None: ...


@runtime_checkable
class KnowledgeRepository(Protocol):
    def get_nodes(self, user_id: str) -> list: ...
    def add_node(self, user_id: str, node_data: dict) -> int: ...
    def get_pending(self, user_id: str) -> list: ...
    def get_records(self, user_id: str, limit: int = 50) -> list: ...
    def record_review(self, user_id: str, node_id: int, quality: int, ease_factor: float, interval_days: int) -> None: ...
    def get_sm2_due(self, user_id: str) -> list: ...


@runtime_checkable
class FocusRepository(Protocol):
    def get_history(self, user_id: str, days: int = 7) -> list: ...
    def start_session(self, user_id: str, planned_minutes: int, subject: str = "") -> int: ...
    def end_session(self, session_id: int, duration_minutes: int, completed: bool) -> None: ...
    def record_event(self, session_id: int, event_type: str, flow_score: float, metadata: dict = None) -> None: ...
    def get_events(self, session_id: int) -> list: ...


@runtime_checkable
class GamificationRepository(Protocol):
    def get_garden(self, user_id) -> dict: ...
    def save_garden(self, user_id, garden_data: dict) -> None: ...
    def get_pet(self, user_id) -> dict: ...
    def save_pet(self, user_id, pet_data: dict) -> None: ...
    def get_achievements(self, user_id) -> list: ...
    def save_achievement(self, user_id, achievement: dict) -> int: ...
    def get_eco(self, user_id) -> dict: ...
    def save_eco(self, user_id, eco_data: dict) -> None: ...


@runtime_checkable
class ClassroomRepository(Protocol):
    def get_session(self, session_id) -> dict | None: ...
    def list_sessions(self, user_id) -> list: ...
    def create_session(self, user_id, course_id: str, teacher_mode: bool = False) -> int: ...
    def update_session(self, session_id, updates: dict) -> None: ...
    def save_quiz_record(self, user_id, quiz_data: dict) -> int: ...
    def get_quiz_records(self, user_id, limit: int = 20) -> list: ...


@runtime_checkable
class CapabilityRepository(Protocol):
    """6-dim user capability profile repository.

    All methods are async. Returns dicts with float/int/str values.
    Empty dicts are valid (new user with no data).
    """
    async def get_knowledge_base(self, user_id: str) -> dict: ...
    async def get_code_skill(self, user_id: str) -> dict: ...
    async def get_cognitive_style(self, user_id: str) -> dict: ...
    async def get_focus_level(self, user_id: str) -> dict: ...
    async def get_learning_goals(self, user_id: str) -> list: ...
    async def get_weakness(self, user_id: str) -> list: ...
    async def aggregate_profile(self, user_id: str) -> dict: ...


@runtime_checkable
class UserRepository(Protocol):
    """User authentication repository.

    Methods that return user records: legacy returns `dict | None`,
    ORM returns ORM model instances (`User | None`). Both satisfy the
    Protocol structurally — callers should treat the return as opaque
    and access fields by attribute (works for both via duck-typing
    or use `.__dict__` for dicts).
    """
    def get_by_username(self, username: str): ...
    def create_user(self, username: str, password_hash: str, preferred_language: str = "zh-CN"): ...
    def record_login(self, user_id, ip: str = "", user_agent: str = "") -> None: ...
    def get_login_history(self, user_id) -> list: ...
