"""Repository Protocol definitions for database merge."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LearningRepository(Protocol):
    async def get_overview(self, user_id: str) -> dict: ...
    async def get_trend(self, user_id: str, days: int) -> list: ...
    async def get_heatmap(self, user_id: str) -> dict: ...
    async def record_session(self, user_id: str, session_data: dict) -> None: ...


@runtime_checkable
class PreferencesRepository(Protocol):
    async def get_preferences(self, user_id: str) -> dict: ...
    async def set_preference(self, user_id: str, key: str, value: dict) -> None: ...
    async def get_settings(self, user_id: str) -> dict: ...
    async def set_setting(self, user_id: str, key: str, value: str) -> None: ...
    async def get_theme(self, user_id: str) -> dict: ...
    async def set_theme(self, user_id: str, theme: str, accent_color: str = "#7c3aed") -> None: ...


@runtime_checkable
class ChatRepository(Protocol):
    async def save_message(self, user_id: str, message: dict) -> int: ...
    async def get_history(self, user_id: str, limit: int) -> list: ...


@runtime_checkable
class CourseProgressRepository(Protocol):
    def get_progress(self, user_id: str, course_id: str) -> dict | None: ...
    def save_progress(self, user_id: str, course_id: str, progress_percent: float, state: dict = None) -> None: ...
    def get_learning_path(self, user_id: str) -> list: ...
    def get_evaluations(self, user_id: str) -> list: ...


@runtime_checkable
class KnowledgeRepository(Protocol):
    def get_nodes(self, user_id: str) -> list: ...
    def add_node(self, user_id: str, node_data: dict) -> int: ...
    def get_pending(self, user_id: str) -> list: ...
    def get_records(self, user_id: str, limit: int = 50) -> list: ...
    def record_review(self, user_id: str, node_id: int, quality: int, ease_factor: float, interval_days: int) -> None: ...
